// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqj-40QZS2kxu_Nb0E800Hv3ioClGyl4E',
    appId: '1:389680836579:web:4623559e30eb1cb9b9fad6',
    messagingSenderId: '389680836579',
    projectId: 'bmi-tracker-ankit-2026',
    authDomain: 'bmi-tracker-ankit-2026.firebaseapp.com',
    storageBucket: 'bmi-tracker-ankit-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPkJkSidve_mxhpJPbdickOsTJ3gFW4Y8',
    appId: '1:389680836579:android:56ed521d8cde4316b9fad6',
    messagingSenderId: '389680836579',
    projectId: 'bmi-tracker-ankit-2026',
    storageBucket: 'bmi-tracker-ankit-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf-YUWFdFjTA67PTZyOD-xeRDYCGvZlow',
    appId: '1:389680836579:ios:882a99edb50b4ce2b9fad6',
    messagingSenderId: '389680836579',
    projectId: 'bmi-tracker-ankit-2026',
    storageBucket: 'bmi-tracker-ankit-2026.firebasestorage.app',
    androidClientId: '389680836579-op796k93qm1f96u1tm971ouk6o8icpvk.apps.googleusercontent.com',
    iosClientId: '389680836579-5gu7siaac0uqce770vl7u2qrgctr143s.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmiTracker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf-YUWFdFjTA67PTZyOD-xeRDYCGvZlow',
    appId: '1:389680836579:ios:882a99edb50b4ce2b9fad6',
    messagingSenderId: '389680836579',
    projectId: 'bmi-tracker-ankit-2026',
    storageBucket: 'bmi-tracker-ankit-2026.firebasestorage.app',
    androidClientId: '389680836579-op796k93qm1f96u1tm971ouk6o8icpvk.apps.googleusercontent.com',
    iosClientId: '389680836579-5gu7siaac0uqce770vl7u2qrgctr143s.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmiTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqj-40QZS2kxu_Nb0E800Hv3ioClGyl4E',
    appId: '1:389680836579:web:fed8d4b86ce8649eb9fad6',
    messagingSenderId: '389680836579',
    projectId: 'bmi-tracker-ankit-2026',
    authDomain: 'bmi-tracker-ankit-2026.firebaseapp.com',
    storageBucket: 'bmi-tracker-ankit-2026.firebasestorage.app',
  );
}
